### ISSUE TITLE
Unity 2020.1b1 crash

### ISSUE THREAD

**Issue by mafaca** [DaZombieKiller/TypeTreeTools#1]
2020.1b1 editor crashes when trying to generate structs.dump in this place
https://github.com/DaZombieKiller/TypeTreeTools/blob/7c423a9f5ac301f581d13f4b3043b1046371247a/Assets/NativeObject.cs#L152-L158

**Comment by DaZombieKiller** [comment]
Yeah, the ProduceAbstractScope thing is a bit of a mess, so I'm not surprised it causes a crash. If you revert to one of the alpha builds of 2020 it should work though. I'll look into this over the next few days.

**Comment by DaZombieKiller** [comment]
I just committed my local changes to the repo. I'm not sure if it's related, but it doesn't appear to crash on 2020.1.0b3, I haven't tested newer versions yet.

**Comment by mafaca** [comment]
Last commit still crashes for 2020.1.0b1, but since it isn't very important for me I just locally disabled dumping of abstract classes

**Comment by mafaca** [comment]
Looks like this one is fixed
